### ISSUE TITLE
camera icon in profile page isn't centered

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-android-client#112]
![Screen Shot 2019-03-18 at 14 49 03](https://user-images.githubusercontent.com/17762105/54534622-0daa6d00-498d-11e9-8a30-fd8cc4c4ebf9.png)

**Comment by lucasvanhalst** [comment]
https://github.com/our-city-app/mobicage-android-client/commit/a53a070fa904cbcf92e4e632746f347edf7bff94
