### ISSUE TITLE
E-mail in news button doesn't work

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-android-client#136]
Sint-Truiden has a news item with an email address in the button. It works on iOS, but doesn't work on Maureen's Android.

NewsItem `722577017`

![Screenshot 2019-05-24 at 10 11 35](https://user-images.githubusercontent.com/17762105/58312912-9f5eac80-7e0c-11e9-96b5-086e2e08c967.png)

**Comment by RubenMattan** [comment]
broken since https://github.com/our-city-app/mobicage-android-client/pull/104

**Comment by RubenMattan** [comment]
fixed in https://github.com/our-city-app/mobicage-android-client/commit/647864cb68448c78bb062950342d1951c4a204da
