### ISSUE TITLE
Markdown parser is more strict than web and iOS

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-android-client#141]
For an example see the What'sUp news items. They look messy.

I would look for a solution where the markdown parser on android is less strict.

**Comment by lucasvanhalst** [comment]
Maybe use https://github.com/noties/Markwon instead of bypass

**Comment by lucasvanhalst** [comment]
Since it doens't seem to be valid markdown (github also doesn't accept spaces before `*` or `**`), not going to fix it. Dashboard now shows how it will look though (so not in bold but with stars).

**Comment by bart-at-mobicage** [comment]
PR https://github.com/our-city-app/mobicage-android-client/pull/143 still needed then?

**Comment by lucasvanhalst** [comment]
I'd still go ahead with it since that library seems better maintained. Bypass hasn't been updated for 2 years.

**Comment by bart-at-mobicage** [comment]
Development of Markwon has only started 2 years ago. Did the markdown specs change in the last 2 years? If not, then I'd rather not update the android library, only because development is still going on.

**Comment by lucasvanhalst** [comment]
fine
