### ISSUE TITLE
Profile address screen doesn't scroll

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-android-client#149]
![Screenshot 2019-06-28 at 13 27 41](https://user-images.githubusercontent.com/17762105/60339178-56b88700-99a8-11e9-84ae-bdd548c62071.png)

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-android-client/commit/b7239e411dd0ccf4c98b05177433d48aed5e8fef
