### ISSUE TITLE
Address improvements

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-android-client#178]
- [x] Make it possible to add an address anywhere in Belgium/Flanders
- [x] Show "work" and "home" as empty addresses to push the user to configure those. Use fa-building and fa-home icons.

**Comment by lucasvanhalst** [comment]
Add the following properties to an address:
-`type` (enum 1,2,3 => home, work, other), to know which address is home etc.
- `icon` -> fixed in case of type home / work, user definable for type 'other'

**Comment by RubenMattan** [comment]
addresses is done op the maps branch
address type will be done by Lucas
