### ISSUE TITLE
Uploaded picture is ridiculously small

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/mobicage-android-client#37]
---

Migrated from https://github.com/rogerthat-platform/rogerthat-android-client/issues/352
Originally created by @bart-at-mobicage on *Fri, 20 Apr 2018 08:25:37 GMT*

---
2 examples of pictures uploaded with the report card of be-zandhoven

![image](https://user-images.githubusercontent.com/17762105/39038744-865e799e-4484-11e8-84ea-f385c7edb26b.png) ![image](https://user-images.githubusercontent.com/17762105/39038757-8abef9e6-4484-11e8-899f-af93d36e05c3.png)

Mobile info:
- hardware model: SM-A320FL (Samsung Galaxy A3 2017)
- os version: 24
- app version: 2.1.3864

**Comment by lucasvanhalst** [comment]
---

Migrated from https://github.com/rogerthat-platform/rogerthat-android-client/issues/352#issuecomment-391610140
Originally created by @RubenMattan on *Thu, 24 May 2018 06:59:52 GMT*

---
Maybe this will help:
- https://stackoverflow.com/questions/28424942/decrease-image-size-without-losing-its-quality-in-android
- http://grishma102.blogspot.be/2016/03/image-compression-in-android.html

**Comment by RubenMattan** [comment]
@bart-at-mobicage can you ask for the original image that way i can investigate more.

**Comment by bart-at-mobicage** [comment]
@RubenMattan, maybe we can just set a minimum size, such that the photo is never smaller than 600px width or height.

**Comment by RubenMattan** [comment]
Would like to know the reason why it happens so we can improve the compression. Was it uploaded via camera or gallery?

**Comment by bart-at-mobicage** [comment]
> Ik heb deze foto getrokken via de app zelf op het moment van de melding en dit via de camera functie van smartphone. Dit is een Samsung Galaxy A5.
> 
> 	Met vriendelijke groeten

**Comment by RubenMattan** [comment]
2 Options i guess:
- I need a Samsung Galaxy A5 to test this
- we move to a new camera library since https://github.com/commonsguy/cwac-cam2 has been deprecated

**Comment by RubenMattan** [comment]
https://github.com/CameraKit/camerakit-android seems the most popular one

**Comment by bart-at-mobicage** [comment]
Lots of effort to change camera lib?

**Comment by RubenMattan** [comment]
I prefer to test on the device first, changing libs include building our own UI and lots of testing
